### ISSUE TITLE
DEX: 25 passing 9 failing

### ISSUE THREAD

**Issue by gluneau** [AcalaNetwork/hardhat-tutorials#49]
Tutorial needs revisions to account for EVM RPC changes

![image](https://user-images.githubusercontent.com/2903505/173157666-2441ac07-3db5-4d19-8286-44d1b67b8a72.png)

**Comment by gluneau** [comment]
- Error: -32603: VM Exception while processing transaction: execution revert UnacceptableLiquidityWithdrawn:
- Error: -32603: VM Exception while processing transaction: execution revert DEX: removeShare is zero
- Error: -32603: VM Exception while processing transaction: execution revert DEX: tokenB is zero address
- Error: -32603: VM Exception while processing transaction: execution revert DEX: tokenA is zero address

![image](https://user-images.githubusercontent.com/2903505/173360817-426aabf6-b5a0-416a-a739-5373d0c10778.png)

**Comment by ThunderDeliverer** [comment]
@gluneau I reran all of the scripts in out tutorials in the local dev network and haven't found a single issue. Could you provide more details on how you get these errors or should we close the issue?
